use_frameworks!

platform :ios, '9.0'

target 'MWPhotoBrowser_LZ_Example' do
  pod 'MWPhotoBrowser_LZ', :path => '../'

  target 'MWPhotoBrowser_LZ_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
